version: '3'

services:
  build: &base
    image: golang
    command: sh -c 'cd /carapace/examples && go build .'
    volumes:
      - '.:/carapace/'
      - 'go:/go/'

  bash:
    build:
      context: .
      dockerfile: docker/Dockerfile.bash
    volumes:
      - '.:/carapace/'

  elvish:
    build:
      context: .
      dockerfile: docker/Dockerfile.elvish
    volumes:
      - '.:/carapace/'

  fish:
    build:
      context: .
      dockerfile: docker/Dockerfile.fish
    volumes:
      - '.:/carapace/'
  
  oil:
    build:
      context: .
      dockerfile: docker/Dockerfile.oil
    volumes:
      - '.:/carapace/'

  powershell:
    build:
      context: .
      dockerfile: docker/Dockerfile.powershell
    volumes:
      - '.:/carapace/'
  
  xonsh:
    build:
      context: .
      dockerfile: docker/Dockerfile.xonsh
    volumes:
      - '.:/carapace/'

  zsh:
    build:
      context: .
      dockerfile: docker/Dockerfile.zsh
    volumes:
      - '.:/carapace/'

volumes:
  go:
