version: '3'

services:
  build:
    image: golang
    command: sh -c 'cd /carapace/example && go build .'
    volumes:
      - '.:/carapace/'
      - 'go:/go/'

  bash:
    build:
      context: .
      dockerfile: Dockerfile.bash
    volumes:
      - '.:/carapace/'

  fish:
    build:
      context: .
      dockerfile: Dockerfile.fish
    volumes:
      - '.:/carapace/'

  powershell:
    build:
      context: .
      dockerfile: Dockerfile.powershell
    volumes:
      - '.:/carapace/'

  zsh:
    build:
      context: .
      dockerfile: Dockerfile.zsh
    volumes:
      - '.:/carapace/'

volumes:
  go:
