version: 2.1

commands:
  run_tests:
    steps:
      - run:
          name: "build"
          command: |
            go get -t -v ./...
            PATH=$PATH:$PWD/bin go test -v ./...
            go build
            go vet
            cd example
            go build .
      - run:
          name: "shellcheck bash"
          command: shellcheck -e SC2046,SC2206,SC2207 <(./example/example _carapace bash)
      - run:
          name: "shellcheck fish"
          command: shellcheck -e SC1064,SC1072,SC1073 <(./example/example _carapace fish)
      - run:
          name: "PSScriptAnayzer powershell"
          command: |
            example _carapace powershell > /tmp/powershell.ps1
            #Invoke-ScriptAnalyzer -Path /tmp/powershell.ps1
      - run:
          name: "shellcheck zsh"
          command: shellcheck -e SC2148,SC2154 <(./example/example _carapace zsh)

jobs:
  go-current:
    docker:
      - image: rsteube/carapace
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run_tests
      - run:
          name: "Check formatting"
          command: diff -u <(echo -n) <(gofmt -d -s .)
  go-previous:
    docker:
      - image: rsteube/carapace
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run_tests
  doc:
    docker:
      - image: rsteube/carapace
    steps:
      - checkout
      - run:
          name: "build docs"
          command: |
            sed -i 's/\[output.linkcheck\]/#[output.linkcheck]/' docs/book.toml
            mdbook build docs
      - run:
          name: "push gh-pages"
          command: |
            cd docs/book/
            git init
            git config user.name rsteube
            git config user.email rsteube@users.noreply.github.com
            git add .
            git commit -m "Initial commit [ci skip]"
            git push --force https://rsteube:${GITHUB_TOKEN}@github.com/rsteube/carapace.git master:gh-pages
  release:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: cd example && curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - go-current
      - go-previous
      - doc:
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
  tags:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
