version: 2

references:
  workspace: &workspace
    /go/src/github.com/rsteube/carapace

  run_tests: &run_tests
    run:
      name: "All Commands"
      command: |
        go get -t -v ./...
        PATH=$PATH:$PWD/bin go test -v ./...
        go build
        go vet
        cd example
        go build .
        curl -Lso shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
        chmod +x shellcheck
        ./shellcheck -e SC2046,SC2207 <(./example _carapace bash)
        ./shellcheck -e SC1064,SC1072,SC1073 <(./example _carapace fish)
        ./shellcheck -e SC2148,SC2154 <(./example _carapace zsh)

jobs:
  go-current:
    docker:
      - image: circleci/golang:1.12
    working_directory: *workspace
    steps:
      - checkout
      - *run_tests
      - run:
          name: "Check formatting"
          command: diff -u <(echo -n) <(gofmt -d -s .)
  go-previous:
    docker:
      - image: circleci/golang:1.11
    working_directory: *workspace
    steps:
      - checkout
      - *run_tests
  go-latest:
    docker:
      - image: circleci/golang:latest
    working_directory: *workspace
    steps:
      - checkout
      - *run_tests

workflows:
  version: 2
  main:
    jobs:
      - go-current
      - go-previous
      - go-latest
