version: 2.1

commands:
  run_tests:
    steps:
      - run:
          name: "build"
          command: |
            go get -t -v ./...
            PATH=$PATH:$PWD/bin go test -v ./...
            go build
            go vet
            cd example
            go build .
      - run:
          name: "install shellcheck"
          command: |
            scversion="stable" # or "v0.4.7", or "latest"
            wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv shellcheck-stable/shellcheck
            mv shellcheck-stable/shellcheck .
            chmod +x shellcheck
      - run:
          name: "shellcheck bash"
          command: ./shellcheck -e SC2046,SC2206,SC2207 <(./example/example _carapace bash)
      - run:
          name: "shellcheck fish"
          command: ./shellcheck -e SC1064,SC1072,SC1073 <(./example/example _carapace fish)
      - run:
          name: "shellcheck zsh"
          command: ./shellcheck -e SC2148,SC2154 <(./example/example _carapace zsh)

jobs:
  go-current:
    docker:
      - image: cimg/go:1.15
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run_tests
      - run:
          name: "Check formatting"
          command: diff -u <(echo -n) <(gofmt -d -s .)
  go-previous:
    docker:
      - image: cimg/go:1.14
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run_tests
  doc:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: "install mdbook"
          command: curl -L "https://github.com/rust-lang/mdBook/releases/download/v0.4.4/mdbook-v0.4.4-x86_64-unknown-linux-gnu.tar.gz" | tar -xvz mdbook
      - run:
          name: "install mdbook"
          command: curl -L "https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v0.7.0/mdbook-linkcheck-v0.7.0-x86_64-unknown-linux-gnu.tar.gz" | tar -xvz mdbook-linkcheck
      - run:
          name: "build docs"
          command: ./mdbook build docs
      - run:
          name: "push gh-pages"
          command: |
            cd docs/book/
            git init
            git config user.name rsteube
            git config user.email rsteube@users.noreply.github.com
            git add .
            git commit -m "Initial commit [ci skip]"
            git push --force https://rsteube:${GITHUB_TOKEN}@github.com/rsteube/carapace.git master:gh-pages
  release:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run: cd example && curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - go-current
      - go-previous
      - doc:
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
  tags:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
